// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: ApiToken
export const ApiToken = z.object({
  // Name: ApiToken.id
  "id": z.string(),
  // Name: ApiToken.name
  "name": z.string(),
  // Name: ApiToken.created
  "created": z.string(),
  // Name: ApiToken.updated
  "updated": z.string(),
});
export type ApiToken = z.infer<typeof ApiToken>;

// Name: AuthClaimQuickConnectCodeBody
export const AuthClaimQuickConnectCodeBody = z.object({
  // Name: AuthClaimQuickConnectCodeBody.code
  "code": z.string(),
});
export type AuthClaimQuickConnectCodeBody = z.infer<typeof AuthClaimQuickConnectCodeBody>;

// Name: AuthFinishProvider
export const AuthFinishProvider = z.object({
  // Name: AuthFinishProvider.token
  "token": z.string(),
});
export type AuthFinishProvider = z.infer<typeof AuthFinishProvider>;

// Name: AuthFinishProviderBody
export const AuthFinishProviderBody = z.object({
  // Name: AuthFinishProviderBody.requestId
  "requestId": z.string(),
  // Name: AuthFinishProviderBody.challenge
  "challenge": z.string(),
});
export type AuthFinishProviderBody = z.infer<typeof AuthFinishProviderBody>;

// Name: AuthFinishQuickConnect
export const AuthFinishQuickConnect = z.object({
  // Name: AuthFinishQuickConnect.token
  "token": z.string(),
});
export type AuthFinishQuickConnect = z.infer<typeof AuthFinishQuickConnect>;

// Name: AuthFinishQuickConnectBody
export const AuthFinishQuickConnectBody = z.object({
  // Name: AuthFinishQuickConnectBody.code
  "code": z.string(),
  // Name: AuthFinishQuickConnectBody.challenge
  "challenge": z.string(),
});
export type AuthFinishQuickConnectBody = z.infer<typeof AuthFinishQuickConnectBody>;

// Name: AuthGetProviderStatus
export const AuthGetProviderStatus = z.object({
  // Name: AuthGetProviderStatus.status
  "status": z.string(),
});
export type AuthGetProviderStatus = z.infer<typeof AuthGetProviderStatus>;

// Name: AuthGetProviderStatusBody
export const AuthGetProviderStatusBody = z.object({
  // Name: AuthGetProviderStatusBody.requestId
  "requestId": z.string(),
  // Name: AuthGetProviderStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetProviderStatusBody = z.infer<typeof AuthGetProviderStatusBody>;

// Name: AuthGetQuickConnectStatus
export const AuthGetQuickConnectStatus = z.object({
  // Name: AuthGetQuickConnectStatus.status
  "status": z.string(),
});
export type AuthGetQuickConnectStatus = z.infer<typeof AuthGetQuickConnectStatus>;

// Name: AuthGetQuickConnectStatusBody
export const AuthGetQuickConnectStatusBody = z.object({
  // Name: AuthGetQuickConnectStatusBody.code
  "code": z.string(),
  // Name: AuthGetQuickConnectStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetQuickConnectStatusBody = z.infer<typeof AuthGetQuickConnectStatusBody>;

// Name: AuthInitiate
export const AuthInitiate = z.object({
  // Name: AuthInitiate.requestId
  "requestId": z.string(),
  // Name: AuthInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthInitiate.challenge
  "challenge": z.string(),
  // Name: AuthInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthInitiate = z.infer<typeof AuthInitiate>;

// Name: AuthInitiateBody
export const AuthInitiateBody = z.object({
  // Name: AuthInitiateBody.providerId
  "providerId": z.string(),
});
export type AuthInitiateBody = z.infer<typeof AuthInitiateBody>;

// Name: AuthProvider
export const AuthProvider = z.object({
  // Name: AuthProvider.id
  "id": z.string(),
  // Name: AuthProvider.displayName
  "displayName": z.string(),
});
export type AuthProvider = z.infer<typeof AuthProvider>;

// Name: AuthQuickConnectInitiate
export const AuthQuickConnectInitiate = z.object({
  // Name: AuthQuickConnectInitiate.code
  "code": z.string(),
  // Name: AuthQuickConnectInitiate.challenge
  "challenge": z.string(),
  // Name: AuthQuickConnectInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthQuickConnectInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthQuickConnectInitiate = z.infer<typeof AuthQuickConnectInitiate>;

// Name: CreateApiToken
export const CreateApiToken = z.object({
  // Name: CreateApiToken.token
  "token": z.string(),
});
export type CreateApiToken = z.infer<typeof CreateApiToken>;

// Name: CreateApiTokenBody
export const CreateApiTokenBody = z.object({
  // Name: CreateApiTokenBody.name
  "name": z.string(),
});
export type CreateApiTokenBody = z.infer<typeof CreateApiTokenBody>;

// Name: GetApiTokens
export const GetApiTokens = z.object({
  // Name: GetApiTokens.tokens
  "tokens": z.array(ApiToken),
});
export type GetApiTokens = z.infer<typeof GetApiTokens>;

// Name: GetAuthProviders
export const GetAuthProviders = z.object({
  // Name: GetAuthProviders.providers
  "providers": z.array(AuthProvider),
});
export type GetAuthProviders = z.infer<typeof GetAuthProviders>;

// Name: Images
export const Images = z.object({
  // Name: Images.original
  "original": z.string(),
  // Name: Images.small
  "small": z.string(),
  // Name: Images.medium
  "medium": z.string(),
  // Name: Images.large
  "large": z.string(),
});
export type Images = z.infer<typeof Images>;

// Name: GetMe
export const GetMe = z.object({
  // Name: GetMe.id
  "id": z.string(),
  // Name: GetMe.email
  "email": z.string(),
  // Name: GetMe.displayName
  "displayName": z.string(),
  // Name: GetMe.role
  "role": z.string(),
  // Name: GetMe.picture
  "picture": Images,
  // Name: GetMe.quickPlaylist
  "quickPlaylist": z.string().nullable(),
});
export type GetMe = z.infer<typeof GetMe>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: UserData
export const UserData = z.object({
  // Name: UserData.id
  "id": z.string(),
  // Name: UserData.displayName
  "displayName": z.string(),
  // Name: UserData.role
  "role": z.string(),
  // Name: UserData.picture
  "picture": Images,
  // Name: UserData.created
  "created": z.string(),
});
export type UserData = z.infer<typeof UserData>;

// Name: GetUser
export const GetUser = z.object({
  // Name: GetUser.user
  "user": UserData,
});
export type GetUser = z.infer<typeof GetUser>;

// Name: UpdateMeBody
export const UpdateMeBody = z.object({
  // Name: UpdateMeBody.displayName
  "displayName": z.string().nullable().optional(),
});
export type UpdateMeBody = z.infer<typeof UpdateMeBody>;

