// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api



func (c *Client) AuthClaimQuickConnectCode(body AuthClaimQuickConnectCodeBody, options Options) (*any, error) {
	path := "/api/v1/auth/quick-connect/claim"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) AuthFinishProvider(body AuthFinishProviderBody, options Options) (*AuthFinishProvider, error) {
	path := "/api/v1/auth/providers/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishProvider](data, body)
}

func (c *Client) AuthFinishQuickConnect(body AuthFinishQuickConnectBody, options Options) (*AuthFinishQuickConnect, error) {
	path := "/api/v1/auth/quick-connect/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishQuickConnect](data, body)
}

func (c *Client) AuthGetProviderStatus(body AuthGetProviderStatusBody, options Options) (*AuthGetProviderStatus, error) {
	path := "/api/v1/auth/provider/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetProviderStatus](data, body)
}

func (c *Client) AuthGetProviders(options Options) (*GetAuthProviders, error) {
	path := "/api/v1/auth/providers"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAuthProviders](data, nil)
}

func (c *Client) AuthGetQuickConnectStatus(body AuthGetQuickConnectStatusBody, options Options) (*AuthGetQuickConnectStatus, error) {
	path := "/api/v1/auth/quick-connect/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetQuickConnectStatus](data, body)
}

func (c *Client) AuthProviderInitiate(body AuthInitiateBody, options Options) (*AuthInitiate, error) {
	path := "/api/v1/auth/providers/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthInitiate](data, body)
}

func (c *Client) AuthQuickConnectInitiate(options Options) (*AuthQuickConnectInitiate, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthQuickConnectInitiate](data, nil)
}

func (c *Client) CreateApiToken(body CreateApiTokenBody, options Options) (*CreateApiToken, error) {
	path := "/api/v1/me/apitokens"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreateApiToken](data, body)
}

func (c *Client) DeleteApiToken(tokenId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/me/apitokens/%v", tokenId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) GetApiTokens(options Options) (*GetApiTokens, error) {
	path := "/api/v1/me/apitokens"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetApiTokens](data, nil)
}

func (c *Client) GetMe(options Options) (*GetMe, error) {
	path := "/api/v1/auth/me"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMe](data, nil)
}

func (c *Client) GetSystemInfo(options Options) (*GetSystemInfo, error) {
	path := "/api/v1/system/info"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetSystemInfo](data, nil)
}

func (c *Client) GetUser(userId string, options Options) (*GetUser, error) {
	path := Sprintf("/api/v1/users/%v", userId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUser](data, nil)
}


func (c *Client) RunTask(taskName string, options Options) (*any, error) {
	path := Sprintf("/api/v1/system/task/%v", taskName)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}


func (c *Client) UpdateMe(body UpdateMeBody, options Options) (*any, error) {
	path := "/api/v1/me"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *ClientUrls) AuthCallback() (*URL, error) {
	path := "/api/v1/auth/providers/callback"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthClaimQuickConnectCode() (*URL, error) {
	path := "/api/v1/auth/quick-connect/claim"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishProvider() (*URL, error) {
	path := "/api/v1/auth/providers/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishQuickConnect() (*URL, error) {
	path := "/api/v1/auth/quick-connect/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviderStatus() (*URL, error) {
	path := "/api/v1/auth/provider/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviders() (*URL, error) {
	path := "/api/v1/auth/providers"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetQuickConnectStatus() (*URL, error) {
	path := "/api/v1/auth/quick-connect/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthProviderInitiate() (*URL, error) {
	path := "/api/v1/auth/providers/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthQuickConnectInitiate() (*URL, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) CreateApiToken() (*URL, error) {
	path := "/api/v1/me/apitokens"
	return c.getUrl(path)
}

func (c *ClientUrls) DeleteApiToken(tokenId string) (*URL, error) {
	path := Sprintf("/api/v1/me/apitokens/%v", tokenId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetApiTokens() (*URL, error) {
	path := "/api/v1/me/apitokens"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMe() (*URL, error) {
	path := "/api/v1/auth/me"
	return c.getUrl(path)
}

func (c *ClientUrls) GetSystemInfo() (*URL, error) {
	path := "/api/v1/system/info"
	return c.getUrl(path)
}

func (c *ClientUrls) GetUser(userId string) (*URL, error) {
	path := Sprintf("/api/v1/users/%v", userId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserImage(userId string, image string) (*URL, error) {
	path := Sprintf("/files/users/images/%v/%v", userId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) RunTask(taskName string) (*URL, error) {
	path := Sprintf("/api/v1/system/task/%v", taskName)
	return c.getUrl(path)
}

func (c *ClientUrls) SseHandler() (*URL, error) {
	path := "/api/v1/system/sse"
	return c.getUrl(path)
}

func (c *ClientUrls) UpdateMe() (*URL, error) {
	path := "/api/v1/me"
	return c.getUrl(path)
}
