// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api

// Name: ApiToken
type ApiToken struct {
	// Name: ApiToken.id
	Id string `json:"id"`
	// Name: ApiToken.name
	Name string `json:"name"`
	// Name: ApiToken.created
	Created string `json:"created"`
	// Name: ApiToken.updated
	Updated string `json:"updated"`
}

// Name: AuthClaimQuickConnectCodeBody
type AuthClaimQuickConnectCodeBody struct {
	// Name: AuthClaimQuickConnectCodeBody.code
	Code string `json:"code"`
}

// Name: AuthFinishProvider
type AuthFinishProvider struct {
	// Name: AuthFinishProvider.token
	Token string `json:"token"`
}

// Name: AuthFinishProviderBody
type AuthFinishProviderBody struct {
	// Name: AuthFinishProviderBody.requestId
	RequestId string `json:"requestId"`
	// Name: AuthFinishProviderBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthFinishQuickConnect
type AuthFinishQuickConnect struct {
	// Name: AuthFinishQuickConnect.token
	Token string `json:"token"`
}

// Name: AuthFinishQuickConnectBody
type AuthFinishQuickConnectBody struct {
	// Name: AuthFinishQuickConnectBody.code
	Code string `json:"code"`
	// Name: AuthFinishQuickConnectBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthGetProviderStatus
type AuthGetProviderStatus struct {
	// Name: AuthGetProviderStatus.status
	Status string `json:"status"`
}

// Name: AuthGetProviderStatusBody
type AuthGetProviderStatusBody struct {
	// Name: AuthGetProviderStatusBody.requestId
	RequestId string `json:"requestId"`
	// Name: AuthGetProviderStatusBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthGetQuickConnectStatus
type AuthGetQuickConnectStatus struct {
	// Name: AuthGetQuickConnectStatus.status
	Status string `json:"status"`
}

// Name: AuthGetQuickConnectStatusBody
type AuthGetQuickConnectStatusBody struct {
	// Name: AuthGetQuickConnectStatusBody.code
	Code string `json:"code"`
	// Name: AuthGetQuickConnectStatusBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthInitiate
type AuthInitiate struct {
	// Name: AuthInitiate.requestId
	RequestId string `json:"requestId"`
	// Name: AuthInitiate.authUrl
	AuthUrl string `json:"authUrl"`
	// Name: AuthInitiate.challenge
	Challenge string `json:"challenge"`
	// Name: AuthInitiate.expiresAt
	ExpiresAt string `json:"expiresAt"`
}

// Name: AuthInitiateBody
type AuthInitiateBody struct {
	// Name: AuthInitiateBody.providerId
	ProviderId string `json:"providerId"`
}

// Name: AuthProvider
type AuthProvider struct {
	// Name: AuthProvider.id
	Id string `json:"id"`
	// Name: AuthProvider.displayName
	DisplayName string `json:"displayName"`
}

// Name: AuthQuickConnectInitiate
type AuthQuickConnectInitiate struct {
	// Name: AuthQuickConnectInitiate.code
	Code string `json:"code"`
	// Name: AuthQuickConnectInitiate.challenge
	Challenge string `json:"challenge"`
	// Name: AuthQuickConnectInitiate.authUrl
	AuthUrl string `json:"authUrl"`
	// Name: AuthQuickConnectInitiate.expiresAt
	ExpiresAt string `json:"expiresAt"`
}

// Name: CreateApiToken
type CreateApiToken struct {
	// Name: CreateApiToken.token
	Token string `json:"token"`
}

// Name: CreateApiTokenBody
type CreateApiTokenBody struct {
	// Name: CreateApiTokenBody.name
	Name string `json:"name"`
}

// Name: GetApiTokens
type GetApiTokens struct {
	// Name: GetApiTokens.tokens
	Tokens []ApiToken `json:"tokens"`
}

// Name: GetAuthProviders
type GetAuthProviders struct {
	// Name: GetAuthProviders.providers
	Providers []AuthProvider `json:"providers"`
}

// Name: Images
type Images struct {
	// Name: Images.original
	Original string `json:"original"`
	// Name: Images.small
	Small string `json:"small"`
	// Name: Images.medium
	Medium string `json:"medium"`
	// Name: Images.large
	Large string `json:"large"`
}

// Name: GetMe
type GetMe struct {
	// Name: GetMe.id
	Id string `json:"id"`
	// Name: GetMe.email
	Email string `json:"email"`
	// Name: GetMe.displayName
	DisplayName string `json:"displayName"`
	// Name: GetMe.role
	Role string `json:"role"`
	// Name: GetMe.picture
	Picture Images `json:"picture"`
	// Name: GetMe.quickPlaylist
	QuickPlaylist *string `json:"quickPlaylist,omitempty"`
}

// Name: GetSystemInfo
type GetSystemInfo struct {
	// Name: GetSystemInfo.version
	Version string `json:"version"`
}

// Name: UserData
type UserData struct {
	// Name: UserData.id
	Id string `json:"id"`
	// Name: UserData.displayName
	DisplayName string `json:"displayName"`
	// Name: UserData.role
	Role string `json:"role"`
	// Name: UserData.picture
	Picture Images `json:"picture"`
	// Name: UserData.created
	Created string `json:"created"`
}

// Name: GetUser
type GetUser struct {
	// Name: GetUser.user
	User UserData `json:"user"`
}

// Name: UpdateMeBody
type UpdateMeBody struct {
	// Name: UpdateMeBody.displayName
	DisplayName *string `json:"displayName,omitempty"`
}

